# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            mothership.one
tagline:          'blog'
description:      'Microservices Blog'
url:              http://mothership.one
baseurl:
commentsystem:    disqus
disqus:           mothership-one

author:
  name:           Daniel BAsten, Patrick Geschinski
  url:            ''

authors:
  axhm3a:
    name: Daniel Basten
    display_name: Daniel Basten
    image: /assets/img/about/daniel_basten.jpg
    github: https://github.com/axhm3a
    about: Software Architekt, Agiler Projektleiter, Software Engineer
  pg2000:
    name: Patrick Geschinski
    display_name: Patrick Geschinski
    image: /assets/img/about/patrick_geschinski.jpg
    github: https://github.com/PG2000
    about: Software Architekt, Agiler Projektleiter, Software Engineer

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:

  - icon:         github
    url:          https://github.com/mothership-one
    desc:         Fork me on github

  - icon:         feed
    url:          http://mothership.one/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

  - title:        Impressum
    url:          /impressum

  - title:        Datenschutz
    url:          /datenschutz

copyright:
  author:         Camporez
  url:            http://camporez.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics: UA-75411916-1

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576

gems:
  - html-proofer
  - jekyll-paginate
  - jekyll-sitemap
