# Harmony Jekyll theme general configurations 

# Base URL
baseurl:

# Site live URL
url: http://mothership.one

# Localhost 
# url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: mothership.one
  # Little description about your site
  description: Microservices Blog
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  meta_description: > # 
   All about microservices
  basetheme: darken # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: axhm3a, pg2000
    email:
    url: http://mothership.one

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-75411916-1

  # Profile links, leave blank to ignore
  social: 
    github:
    twitter:
    facebook:
    gplus:
    dribble:
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
